name: Commit Moderation

on:
  push:

jobs:
  signoff:
    name: Signoff Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check commit
        run: |
          git show HEAD --no-patch | grep -q "Signed-off-by: " && exit 0
          echo "::error::You should sign off to commit!"
          exit 1

